[profile.default]
solc = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]
no_match_path = "*/integration/*"
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
optimizer_runs = 1000000

[profile.integration]
no_match_path = ""
match_path = "*/integration/*"

[profile.lite.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = 'xca'

[rpc_endpoints]
local = "${LOCAL_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
